# MinIO — standalone mode, aakp-data namespace
mode: standalone

auth:
  rootUser: aakp-admin
  rootPassword: aakp-minio-secret

defaultBuckets: "bronze,archive"

persistence:
  enabled: true
  size: 10Gi

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m

service:
  type: ClusterIP
  port: 9000

consoleService:
  type: ClusterIP
  port: 9001

metrics:
  serviceMonitor:
    enabled: false
