apiVersion: v1
kind: Secret
metadata:
  name: aakp-fuseki-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aakp-fuseki.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.fuseki.adminPassword | quote }}
