apiVersion: v1
kind: Service
metadata:
  name: {{ include "aakp-fuseki.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aakp-fuseki.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3030
      protocol: TCP
      name: http
  selector:
    {{- include "aakp-fuseki.selectorLabels" . | nindent 4 }}
